version: '3.8'

services:
  bot:
    build: .
    command: sh -c "python -m bot_core"
    volumes:
      - .:/project/
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - tt_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${PG_PORT}:5432
    env_file:
      - ./.env

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@admin.admin"
      - "PGADMIN_DEFAULT_PASSWORD=admin"
    ports:
      - "5050:80"
  redis:
    image: redis:alpine
    env_file:
      - .env
    environment:
      - HOST=${REDIS_HOST},
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  tt_data: